version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_KEY=base64:W1VQ15meOCj8sNk7+SiZymPNEJ4lH3TxQ+cIPttvpA4=
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=studyhouse-test
      - DB_USERNAME=user
      - DB_PASSWORD=password

  db:
    image: mysql:5.7
    container_name: lumen_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studyhouse-test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
